---

- include: install.yml
  tags: [jupyterhub]

- include: config.yml
  tags: [jupyterhub, config]

- include: service.yml
  tags: [jupyterhub, service]

- include: jupyter.yml
  tags: [jupyterhub, jupyter, config]
